# Generated by Django 4.1.3 on 2022-11-12 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conex', '0002_camisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='pant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=3)),
                ('valor', models.IntegerField()),
                ('cant', models.IntegerField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conex.prod')),
            ],
        ),
    ]
