# Generated by Django 4.1.3 on 2022-11-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conex', '0003_pant'),
    ]

    operations = [
        migrations.AddField(
            model_name='camisa',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
