# Generated by Django 4.1.3 on 2022-11-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conex', '0004_camisa_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pant',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
