# Generated by Django 4.1.3 on 2022-11-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conex', '0005_pant_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb', models.CharField(max_length=30)),
                ('descrip', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=3)),
                ('valor', models.IntegerField()),
                ('cant', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.RemoveField(
            model_name='pant',
            name='prod_id',
        ),
        migrations.DeleteModel(
            name='camisa',
        ),
        migrations.DeleteModel(
            name='pant',
        ),
        migrations.DeleteModel(
            name='prod',
        ),
    ]
